config/routes.rb
Rails.application.routes.draw do

  
  mount Ckeditor::Engine => '/ckeditor'
  # get 'posts/index'
  # get 'posts/show'
  # get 'posts/new'
  # get 'posts/create'
  # get 'posts/edit'
  # get 'posts/update'
  # get 'posts/delete'
  resources :posts  do
    resources :comments
  end
  root to: 'users#welcome'

  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmation: 'confirmation'
    }

  namespace :admin do
    root to: 'users#welcome'
    resources :users
    resources :posts  do
      resources :comments
    end 
    get '/users/:id/posts', to: 'users#user_post', as: 'user_post'
  end

  #get '/users/:id/posts', to: 'users#user_post', as: 'user_post' #custom routes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/base/_control_sidebar.html.erb
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane active" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:;">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:;">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="pull-right-container">
                    <span class="label label-danger pull-right">70%</span>
                  </span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>

app/views/base/_footer.html.erb
<footer class="main-footer">
  <!-- Default to the left -->
  <strong>WebApplication &copy; 2022 <a href="#">Company</a>.</strong> All rights reserved.
</footer>

app/views/base/_header.html.erb
<header class="main-header">
  <div class="logo">
    <span class="logo-mini"><b>A</b>LT</span>
    <span class="logo-lg"><b>Admin</b>LTE</span>
  </div>
  <nav class="navbar navbar-static-left">
    <a class="sidebar-toggle" data-toggle="push-menu" role="button">
    <span class="sr-only">Toggle navigation</span>
    </a>

  
    <div class="pull-right">
      <% if current_user.present? %>
         <h4><b><%= link_to "Sign out", destroy_user_session_path, method: 'delete',style:"color:white"%></b></h4> 
      <%end%>
  
  </nav>

</header>

app/views/base/_sidebar.html.erb
<aside class="main-sidebar">
  <section class="sidebar">
    <span class= "logo-mini"><%= link_to "", admin_user_path(current_user.id), class: "bi bi-person-circle" %></span>
    <span class="logo-lg"><b><%= link_to current_user.name, admin_user_path(current_user.id) %></b></span>
      <!--search form (Optional) ->
        <form action="#" method="get" class="sidebar-form">
          <div class="input-group">
            <input type="text" name="q" class="form-control" placeholder="Search...">
            <span class="input-group-btn">
              <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
              </button>
            </span>
          </div>
        </form>
      <--/.search form -->
    <ul class="sidebar-menu sidebar" data-widget="tree">
      <li>
        <span class="logo-mini"><%= link_to "", admin_root_path, class:"bi bi-house-door-fill"%></span>
        <span class="logo-lg"><%= link_to "Home", admin_root_path%></span>
      </li>
      <li>
        <span class="logo-mini"><%= link_to "", admin_users_path, class:"bi bi-person-lines-fill"%></span>
        <span class="logo-lg"><%= link_to "Users", admin_users_path%></span>
      </li>
      <li><span class="logo-mini"><%= link_to "", admin_posts_path, class:"bi bi-postcard-fill"%></span>
        <span class="logo-lg"><%= link_to "Posts", admin_posts_path%></span>
      </li>
    </ul>
  </section>
    <!-- /.sidebar -->
</aside>