config/routes.rb
Rails.application.routes.draw do

  
  mount Ckeditor::Engine => '/ckeditor'
  # get 'posts/index'
  # get 'posts/show'
  # get 'posts/new'
  # get 'posts/create'
  # get 'posts/edit'
  # get 'posts/update'
  # get 'posts/delete'
  resources :posts  do
    resources :comments
  end
  root to: 'users#welcome'

  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmation: 'confirmation'
    }

  namespace :admin do
    root to: 'users#welcome'
    resources :users
    resources :posts  do
      resources :comments
    end 
    get '/users/:id/posts', to: 'users#user_post', as: 'user_post'
  end

  #get '/users/:id/posts', to: 'users#user_post', as: 'user_post' #custom routes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<footer class="footer text-center text-lg-star">

  <div class="text-center p-3" style= "background-color: rgba(0, 0, 0, 0.2);">
      <i style="color:green;"> Made by- MatrixMarketer'sTrainee</i>
  </div>

</footer>

app/views/shared/_header.html.erb
<header class=" header navbar navbar-fixed-top navbar-inverse" style= "background-color: rgba(0, 0, 0, 0.2);">
      <div class="container-fluid" >
            <h5>
            <% if current_user.present? %>
                  <%if (current_user.role == "superadmin") || (current_user.role == "admin")%>
                         <%= link_to "Admin", admin_users_path%>
                  <%else%>
                         <%= link_to "Create Post", new_post_path%>
                        | <%= link_to "Posts", posts_path%>
                  <%end%>
            <%else%>
                  <%= link_to "Posts", posts_path%>
            <%end%></h5>
            
            <nav class="navbar-fixed-top">
                  <div class="pull-right">
                        <% if current_user.present? && current_user.role.eql?("user") %>
                              <b><%= link_to current_user.name, "/users/#{current_user.id}", class:" bi bi-person-circle"%></b> |
                              <%= link_to "Sign out", destroy_user_session_path, method: 'delete'%> 
                        <%end%>
                  </div>
            </nav>
      </div>
</header>

 