config/routes.rb
Rails.application.routes.draw do

  
  mount Ckeditor::Engine => '/ckeditor'
  # get 'posts/index'
  # get 'posts/show'
  # get 'posts/new'
  # get 'posts/create'
  # get 'posts/edit'
  # get 'posts/update'
  # get 'posts/delete'
  resources :posts  do
    resources :comments
  end
  root to: 'users#welcome'

  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmation: 'confirmation'
    }

  namespace :admin do
    root to: 'users#welcome'
    resources :users
    resources :posts  do
      resources :comments
    end 
    get '/users/:id/posts', to: 'users#user_post', as: 'user_post'
  end

  #get '/users/:id/posts', to: 'users#user_post', as: 'user_post' #custom routes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    paginates_per 25
    
    has_many :comments, as: :commentable, dependent: :destroy
    belongs_to :user
    
    has_attached_file :image
    validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }, presence: true
   
    validates :title, presence: true
    
    validates :description, presence: true

   
    scope :published, -> { where( published: true ) }
    scope :unpublished, -> { where( published: false ) }

    
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
before_action :required_post, only: [:show, :edit, :update, :destroy]
  
  def index
    @posts = Post.all.order("id desc").page(params[:page]).per(3)
   
  end

  def show
    
  end

  def new
    @post = Post.new
   
  end

  def create
    @post = Post.new(post_params)
   if @post.save
        redirect_to  admin_posts_path
     else
       render 'new'
     end
  end

  def edit
    
  end

  def update
    if @post.update(edit_params)
        redirect_to admin_posts_path(@post)
    else
        render 'edit'
    end
  end

  def destroy
      @post.destroy
      redirect_to admin_posts_path
  end

  private
  def post_params
    params.required(:post).permit(:title, :description, :image, :published, :user_id)
  end

  def edit_params
    params.required(:post).permit(:title, :description, :image, :published)
  end

  def required_post
    @post = Post.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_action :authenticate_user!
  before_action :required_post, only: [:show, :edit, :update, :destroy]
  
  def index
    @posts = Post.published.order("id desc").page(params[:page]).per(3)
    if current_user.present?
      @posts = Post.published.or(Post.unpublished.where(user_id: current_user.id)).order("id desc").page(params[:page]).per(3)
    end
    authorize @posts
  end

  def show
    
  end

  def new
    @post = Post.new
    authorize @post  
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    authorize @post
   if @post.save
        redirect_to  posts_path
     else
       render 'new'
     end
  end

  def edit
    
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.required(:post).permit(:title, :description, :image, :published, :user_id)
  end

  def required_post
    @post = Post.find(params[:id])
    authorize @post 
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<% if @post.errors.any?%>
    <% @post.errors.full_messages.each do |msg| %>
        <p style="color: red;"><%= msg %></p>
    <% end %>
<%end%><br>
<%= form_for @post do |f| %>
    
    <div class="form">
    <%= f.label :Title %>
    <%= f.text_field :title %><br>
    </div>
    <div class="form">
    <%= f.label :Description %>
    <%= f.cktext_area  :description %><br>
    </div>
    <div class="form">
    <%= f.label :Image %>
    <%= f.file_field :image %><br>
    </div>
    <div class="form">
    <%= f.label :Published%>
    <%= f.check_box :published %><br>
    </div>
    <div class="from">
    <%= f.text_field :user_id, value: current_user.id, class:'d-none'%>
    </div>
    <div class="text">
    <%= f.submit %>
    </div>

<% end %>

app/views/posts/index.html.erb
<% if @posts.present? %>
    <h2>Posts</h2>
    <div class="container-fluid">
        <table class="table table-striped table-image">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">S.no.</th>
                    <th scope="col">User Name</th>
                    <th scope="col">Title</th>
                    <th scope="col">Image</th>
                    <th scope="col">Description</th>
                    <th scope="col">Published</th>
                    <% if current_user.present?%>
                        <th scope="col">Action</th>
                        <th scope="col">Comments</th>
                    <%end%>
                </tr>
            </thead>
            <tbody>  
                <% @posts.each_with_index do |posts, i|%>
                <tr>
                    <th scope="row"><%= i+1 %></th>
                    <td> <%= posts.user.name%></td>
                    <td><%= posts.title %></td>
                    <td><% if posts.image.exists? %>
                            <%= image_tag(posts.image.url, width: "150", height: "150")%>
                        <%end%>
                    </td>
                    <td><%= strip_tags( posts.description ) %></td>
                    <td><%= posts.published%></td>
                    <%if current_user.present?%>
                        <td><%= link_to "", post_path(posts.id), class: "bi bi-eye-fill"%>
                            <% if current_user.role == "superadmin"  %>
                                <%= link_to "", "/posts/#{posts.id}", method: "delete", data: {confirm: "are you sure ?"}, class: "bi bi-trash3-fill"%>
                                <%= link_to "", edit_post_path(posts.id), class: "bi bi-pencil-square" %>
                            <%end%>
                            <% if (current_user.role == "admin" || current_user.role == "user") && (current_user.name == posts.user.name) %>
                                <%= link_to "", edit_post_path(posts.id), class: "bi bi-pencil-square" %>
                                <%= link_to "", "/posts/#{posts.id}", method: "delete", data: {confirm: "are you sure ?"}, class: "bi bi-trash3-fill"%>
                            <%end%>
                        </td>
                        <td><%if posts.comments.present? %>
                                <%= link_to posts.comments.count, "/posts/#{posts.id}/comments", class: "bi bi-chat-right-dots-fill"%>
                            <%else%>
                                No comments!
                            <%end%>
                        </td>
                    <%end%>
                </tr>
                <%end%>
            </tbody>
        </table>
    </div>
<%else%>
    <h5> There is no post..!</h5>
<%end%>
<%= paginate @posts%>

<%#= paginate @posts, left: 1, right: 3 %>
<%#= paginate @posts, outer_window: 3  %>
<b><%#= link_to 'Back', users_path%></b>
          

app/views/posts/new.html.erb
<% if @post.errors.any?%>
    <% @post.errors.full_messages.each do |msg| %>
        <p style="color: red;"><%= msg %></p>
    <% end %>
<%end%><br>

<%= form_for @post do |f| %>
    
    <div class="form">
    <%= f.label :Title %>
    <%= f.text_field :title %><br>
    </div>
    <div class="form">
    <%= f.label :Description %>
    <%= f.cktext_area :description %><br>
    </div>
    <div class="form">
    <%= f.label :Image %>
    <%= f.file_field :image %><br>
    </div>
    <div class="form">
    <%= f.label :Published%>
    <%= f.check_box :published %><br>
    </div>
    <div class="from">
    <%= f.text_field :user_id, value: current_user.id, class:'d-none'%>
    </div>
    <div class="text">
    <%= f.submit %>
    </div>

<% end %>

app/views/posts/show.html.erb
<p>Post-by:<%= @post.user.name %></p>
<div class = "container-fluid bg-secondary text-white">
<div class= "row">
    <div class = "col-9">
        <div class= "pb-3">
            <b style="color:black">Title :</b> <%= @post.title %>
        </div>
   </div>
    <div class = "col-6 ">
       <%#= image_tag(@post.image.url, width: "300", height: "300")%>
        <b style="color:black">Description :</b><%=strip_tags(@post.description)%>
    </div>
    <div class = "col-3">
        <%= image_tag(@post.image.url, width: "450", height: "400")%>
    </div>
    <div class="col-4">
    <b style="color:black">Published :</b><%= @post.published%>
    </div>
</div>

<b style="color:black">Comments:</b><br />
    <ul>
        <% @post.comments.each do |comments|%>
           <li style="color:black"><%= comments.body %> | by- <i ><%= comments.user.name%> </i>| 
                <%if current_user.present? %>
                    <% if(current_user.id == @post.user.id || current_user.id == comments.user.id) %>
                        <%= link_to "", "/posts/#{@post.id}:/comments/#{comments.id}", method: "delete", data: {confirm: "are you sure"}, class: "bi bi-trash3-fill icon-green", style:"color:red"%>
                        <%= link_to "", "/posts/#{@post.id}/comments/#{comments.id}/edit", class: "bi bi-pencil-square", style:"color:blue"%>
                    <%elsif current_user.role == "admin" || current_user.role == "superadmin" %>
                        <%= link_to "", "/posts/#{@post.id}:/comments/#{comments.id}", method: "delete", data: {confirm: "are you sure"}, class: "bi bi-trash3-fill",style:"color:red"%>                        
                        <%= link_to "", "/posts/:#{@post.id}/comments/#{comments.id}/edit", class: "bi bi-pencil-square", style:"color:blue"%>
                    <%end%>
                <%end%>
            </li>
        <%end%>
    <ul>
<div class = ""><%= render partial: "comments/form"%></div>
</div >
<b><%= link_to 'Back', posts_path%></b>
 