config/routes.rb
Rails.application.routes.draw do

  
  mount Ckeditor::Engine => '/ckeditor'
  # get 'posts/index'
  # get 'posts/show'
  # get 'posts/new'
  # get 'posts/create'
  # get 'posts/edit'
  # get 'posts/update'
  # get 'posts/delete'
  resources :posts  do
    resources :comments
  end
  root to: 'users#welcome'

  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmation: 'confirmation'
    }

  namespace :admin do
    root to: 'users#welcome'
    resources :users
    resources :posts  do
      resources :comments
    end 
    get '/users/:id/posts', to: 'users#user_post', as: 'user_post'
  end

  #get '/users/:id/posts', to: 'users#user_post', as: 'user_post' #custom routes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, 
         :omniauthable, omniauth_providers: [:google_oauth2]
         
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  validates :email, uniqueness: true, presence: true
  validates :name, presence: true
 
  validates :mobile_number,   presence: true, numericality: true, length: { minimum: 10, maximum: 12  }


  belongs_to :role_user, optional: true
  #after_create :set_role

  enum role: [:superadmin, :user, :admin]
  #enum role: [:superadmin]
  after_initialize :set_default_role, if: :new_record?

  # scope :published, -> { where( published: true ) }
  # scope :unpublished, -> { where( published: false ) }

  def self.search(search)
    where("email LIKE ? OR name LIKE ? ", "%#{search}%", "%#{search}%")
  end

  # def self.from_omniauth(access_token)
  #   data = access_token.info
  #   user = User.where(email: data['email']).first
  # end

  def self.from_omniauth(auth)
    where(provider: auth.provider).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  private
  def set_default_role
      self.role ||= :user
  end

# def self.from_omniauth(auth)
  #   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  #     user.email = auth.info.email
  #     user.password = Devise.friendly_token[0, 20]
  #     user.name = auth.info.name 
  #   end
  # end


  # def self.from_google(email:, name:, uid:)
  #   return nil unless email =~ /@gmial.com\z/
  #   create_with(uid: uid, name: name).find_or_create_by!(email: email)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
   
    before_action :authenticate_user!
    before_action :set_user, only: [:show, :destroy, :edit, :update, :user_post]
    #before_action :set_post, only: [:user_post]
    def index
      if params[:search]
        @users = User.search(params[:search]).order("created_at DESC").page(params[:page]).per(4)
      else
        @users = User.all.order('created_at DESC').page(params[:page]).per(4)
      end
    end
  
    def destroy
      @user.destroy
       
      redirect_to admin_users_path
    end
  
    def edit 
    end

    def update 
      if @user.update(user_params)
          redirect_to admin_users_path
      else 
        render 'edit'
      end
    end


    def welcome
    end

    def user_post
    end
  
    def show
    end
  
    
    private
    def set_user
      @user = User.find(params[:id])
    end
  
    def user_params
      params.required(:user).permit(:name, :mobile_number, :role)
    end
  
  end
  

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  
  # if User.find_by_email(params[:user][:email]).present?
  #   if User.find_by_email(params[:user][:email]).try(:confirmed_at).present?
  #    super
  #   else
  #    redirect_to :back, notice:  'Please confirm your email first'
  #   end
  #  else
  #   redirect_to :back, notice:  'User not found'
  #  end
  # end
  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

   protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource)
    new_user_session_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end
  def google_oauth2
    user = User.from_omniauth(auth)

    if user.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect user, event: :authentication
    else
      flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_user_session_path
    end
  end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

   protected
# The path used when OmniAuth fails
  def after_omniauth_failure_path_for(_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end


  
  
  # app/controllers/users/omniauth_callbacks_controller.rb:

  private
  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
   before_action :configure_account_update_params, only: [:edit, :update]
    protected

    # def update_resource(resource, account_update_params)
    #   resource.update_without_password(account_update_params)
    # end
  
    # def after_update_path_for(resource)
    #   account_user_path(current_account, current_user)
    # end
  
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, except: [:current_password, :password])
    # end
  
    def account_update_params
      params.require(:user).permit(:name, :email)
    end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :destroy, :edit, :update]
 
  def index
    if params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
    else
      @users = User.all.order('created_at DESC')
    end
    authorize @users
  end

  def welcome

  end

  def show
    
  end

  def destroy
    #@user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  def edit 
  end

  def update 
    @user.update(user_params)
    redirect_to users_path
  end

  
  private
  def set_user
    @user = User.find(params[:id])
    authorize @user
  end

  def user_params
    params.required(:user).permit(:name, :mobile_number, :role)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<%= form_for [:admin, @user] do |f| %>
  <div class="field">
    <%= f.label :name%><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mobile_number%><br />
    <%= f.number_field :mobile_number%>
  </div>
  <div class="field">
    <%= f.label :role %>
    <%= f.select(:role, [['User', 'user'], ['Admin', 'admin']]) %>
    <%#= f.select :role, options_for_select(User.roles.map {|key, value| [key.titleize, User.roles.key(value)]}, @user.role) %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<%end%>

<b><%= link_to "Back", admin_users_path %></b> 

app/views/admin/users/index.html.erb
<p>User's list</p>
<p class= "search-field">
    <%= form_tag(admin_users_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Users" %>
        <%= submit_tag "Search" %>
    <% end %>
</p>
<div class="container-fluid">
    <table class="table table-striped table-image">
        <thead class="thead-dark">
            <tr>
                <th scope ="col"> User Id</th>
                <th scope="col">User Name</th>
                <th scope="col">Role</th>
                <th scope="col"> Email-id</th>
                <% if current_user.present?%> 
                    <th scope="col">Action</th>
                <%end%>
            </tr>
        </thead>
        <tbody>
            <% @users.each do |u|%>
                <tr>
                    <td><%= u.id%></td>
                    <td><%= u.name %></td>
                    <td><%= u.role%></td>
                    <td><%= u.email%></td>
                    <td><%= link_to "", "/admin/users/#{u.id}", class: "bi bi-eye-fill" %>
                            <% if current_user.role == "superadmin"%>
                                <%= link_to "", "/admin/users/#{u.id}", method: "delete", data: {confirm: "are you sure ?"}, class: "bi bi-trash3-fill"%>
                                <% if current_user.name.eql?(u.name)%>
                                    <%= link_to "", edit_user_registration_path(u.id),class: "bi bi-pencil-square"%>
                                <%else%>
                                    <%= link_to "", edit_admin_user_path(u.id),class: "bi bi-pencil-square"%>
                                <%end%>
                            <%end%>
                            <% if current_user.role == "admin" && current_user.id.eql?(u.id) %>
                                <%= link_to "", "/admin/users/#{u.id}", method: "delete", data: {confirm: "are you sure ?"}, class:"bi bi-trash3-fill"%>
                                <%= link_to "", edit_user_registration_path(u.id), class: "bi bi-pencil-square"%>
                            <%end%>
                        <%= button_to "Posts", "/admin/users/#{u.id}/posts", method: "get", class: "btn btn-info" %>
                    </td>
                </tr>
            <%end%>
        </tbody>
    </table> 
</div>
<%= paginate @users%>

app/views/admin/users/show.html.erb
<div>
    <table class="user-table center" style="width:90%">
        <tr>
            <th colspan="5"><b>Details of <%=@user.name%></b></th>
        </tr>
        <tr>
            <th>Name</th>
            <th>Role</th>
            <th>Mobile Number</th>
            <th>Email</th>
        </tr>
        <tr>
            <td><%= @user.name%></td>
            <td><%= @user.role%></td>
            <td><%= @user.mobile_number%></td>
            <td><%= @user.email%>   
        </tr>
    </table>
<div>
<b><%= link_to "Back", admin_users_path%></b

app/views/admin/users/user_post.html.erb
<% if @user.posts.present? %>
    <h2>Posts</h2>
    <div class="container-fluid">
        <table class="table table-striped table-image">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">S.no.</th>
                    <th scope="col">User Name</th>
                    <th scope="col">Title</th>
                    <th scope="col">Image</th>
                    <th scope="col">Description</th>
                    <th scope="col">Published</th>
                    <% if current_user.present?%>
                        <th scope="col">Action</th>
                        <th scope="col">Comment</th>
                    <%end%>
                </tr>
            </thead>
            <tbody>  
                <% @user.posts.each_with_index do |posts, i|%>
                <tr>
                    <th scope="row"><%= i+1 %>
                    <td> <%= posts.user.name%></td>
                    <td><%= posts.title %></td>
                    <td><% if posts.image.exists? %>
                            <%= image_tag(posts.image.url, width: "150", height: "150")%>
                        <%end%>
                    </td>
                    <td><%= strip_tags( posts.description ) %></td>
                    <td><%= posts.published%></td>
                    <%if current_user.present?%>
                        <td><%= link_to "", admin_post_path(posts.id), class: "bi bi-eye-fill"%>
                            <% if current_user.role == "superadmin"  %>
                                <%= link_to "", "/admin/posts/#{posts.id}", method: "delete", data: {confirm: "are you sure ?"}, class: "bi bi-trash3-fill"%>
                                <%= link_to "", edit_admin_post_path(posts.id), class: "bi bi-pencil-square" %>
                            <%end%>
                            <% if (current_user.role == "admin" || current_user.role == "user") && (current_user.name == posts.user.name) %>
                                <%= link_to "", edit_admin_post_path(posts.id), class: "bi bi-pencil-square" %>
                                <%= link_to "", "/admin/posts/#{posts.id}", method: "delete", data: {confirm: "are you sure ?"}, class: "bi bi-trash3-fill"%>
                            <%end%>
                        </td>
                        <td><%if posts.comments.present? %>
                                <%= link_to posts.comments.count, "/admin/posts/#{posts.id}/comments", class: "bi bi-chat-right-dots-fill"%>
                            <%else%>
                                No comments!
                            <%end%>
                        </td>
                    <%end%>
                </tr>
                <%end%>
            </tbody>
        </table>
    </div>
<%else%>
    <h5> There is no post..!</h5>
<%end%>

<b><%= link_to "Back", admin_users_path%>
          

app/views/admin/users/welcome.html.erb
<h3>Welcome <%= current_user.name%>.</h3>
This is the Post's WebApplication
<!--% if current_user.present? %>
    <%= link_to "Create Post", new_admin_post_path%>
<%end%-->